---

- name: Add apache global configuration.
  template:
    src: "apache2.conf.j2"
    dest: "{{ apache_conf_path }}/apache2.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods.
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: "path={{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"


- name: Add apache remoteip configuration.
  template:
    src: "remoteip.conf.j2"
    dest: "{{ apache_conf_path }}/conf-available/remoteip.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_haproxy_ip is defined

- name: Add symlink for remoteip configuration.
  file:
    src: "{{ apache_conf_path }}/conf-available/remoteip.conf"
    dest: "{{ apache_conf_path }}/conf-enabled/remoteip.conf"
    state: link
  notify: restart apache
  when: apache_haproxy_ip is defined


- name: Generate a Self Signed openssl_privatekey certificate
  openssl_privatekey:
    path: "/etc/ssl/private/{{ item.servername }}.key"
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_vhosts_ssl|length>0

- name: Generate a Self Signed openssl_csr certificate
  openssl_csr:
    path: "/etc/ssl/{{ item.servername }}.csr"
    privatekey_path: "/etc/ssl/private/{{ item.servername }}.key"
    common_name: "{{ item.servername }}"
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_vhosts_ssl|length>0

- name: Generate a Self Signed openssl_certificate certificate
  openssl_certificate:
    path: "/etc/ssl/certs/{{ item.servername }}.crt"
    privatekey_path: "/etc/ssl/private/{{ item.servername }}.key"
    csr_path: "/etc/ssl/{{ item.servername }}.csr"
    provider: selfsigned
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_vhosts_ssl|length>0


- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost
