
- name: stop tomcat instance
  service:
    name: "{{ tomcat_service_name }}"
    state: stopped

# clonar los repositorio de VIVO y Vitro
- name: clone/update apps 
  include_role:
    name: git
  vars: 
    git_repo: "{{ item.url }}"
    git_app_name: "{{ item.name }}"
  with_items:
    - { url: "http://gitlab.upr.edu.cu/vivo/vivo.git", name: vivo}
    - { url: "http://gitlab.upr.edu.cu/vivo/vitro.git", name: vitro}
    - { url: "http://gitlab.upr.edu.cu/vivo/vivo-solr.git", name: vivo-solr}

# editar el fichero install-settings.xml
- name: template install-settings.xml
  template:
    src: templates/install-settings.xml.j2
    dest: "{{ vivo_dir }}/installer/install-settings.xml"


- name: Execute mvn install
  shell: "mvn install -s install-settings.xml"
  args:
    chdir: "{{ vivo_dir }}/installer/"


- name: template runtime.properties
  template:
    src: templates/runtime.properties.j2
    dest: "{{ vivo_dir }}/home/config/runtime.properties"

- name: template applicationSetup.n3
  template:
    src: templates/applicationSetup.n3.j2
    dest: "{{ vivo_dir }}/home/config/applicationSetup.n3"

- name: set permisions to vivo home directory
  file:
      path: "{{ vivo_dir }}/home" 
      group: "{{tomcat_group}}"
      owner: "{{tomcat_user}}" 


- name: update  /etc/security/limits.conf to give more threads than are permitted (apache)
  lineinfile:
    path: /etc/security/limits.conf
    firstmatch: yes
    regexp: '^apache '
    insertafter: '^#apache '
    line: apache hard nproc 400

- name: update  /etc/security/limits.conf to give more threads than are permitted (tomcat)
  lineinfile:
    path: /etc/security/limits.conf
    firstmatch: yes
    regexp: '^tomcat '
    insertafter: '^#tomcat '
    line: tomcat hard nproc 1500

- name: apt install python-lxml
  apt:
      update_cache: yes
      name: python3-lxml


- name: update "Connector" in server.xml of tomcat to adapt it to vivo
  xml:
    path: "{{ tomcat_dir }}/conf/server.xml"
    xpath: /Server/Service/Connector[@protocol="AJP/1.3"]
    attribute: "{{ item.attr }}"
    value: "{{ item.value }}"
  with_items:
    - { attr: "redirectPort", value: "{{ tomcat_ssl_connector_port }}" }
    - { attr: "connectionTimeout", value: "{{ tomcat_connection_timeout }}" }
    - { attr: "maxThreads", value: "{{ tomcat_max_threads }}" }
    - { attr: "keepAliveTimeout", value: "{{ tomcat_keep_alive_timeout }}" }


- name: update "Host" in server.xml of tomcat to adapt it to vivo
  xml:
    path: "{{ tomcat_dir }}/conf/server.xml"
    xpath: /Server/Service/Engine/Host[@name="localhost"]
    attribute: "{{ item.attr }}"
    value: "{{ item.value }}"
  with_items:
    - { attr: "appBase", value: "webapps" }
    - { attr: "DeployOnStartup", value: "false" }
    - { attr: "unpackWARs", value: "true" }
    - { attr: "autoDeploy", value: "false" }
    - { attr: "xmlValidation", value: "false" }
    - { attr: "xmlNamespaceAware", value: "false" }


- name: set_children "Host" in server.xml of tomcat to adapt it to vivo
  xml:
    path: "{{ tomcat_dir }}/conf/server.xml"
    xpath: /Server/Service/Engine/Host[@name="localhost"][@xmlNamespaceAware="false"]
    input_type: xml
    set_children:
      - <Alias>{{ alias }}</Alias>
      - <Context path=""
            docBase="{{ tomcat_dir }}/webapps/{{ app_name }}" reloadable="true" cookies="true" >
                <Environment type="java.lang.String" name="vitro/home" value="{{ vivo_dir }}/home" override="true"/>
                <Manager pathname="" /> 
          </Context>


- name: restart tomcat instance
  service:
    name: "{{ tomcat_service_name }}"
    state: restarted