- name: apply common configuration to all nodes
  hosts: vivo, solr, mysql
  remote_user: root
  roles:
    - role: crai-common
      vars:
        apt_protocol: "{{ proxy__protocol }}"
        apt_repo: "{{ ubuntu_repo }}"
        apt_so: ubuntu
        apt_dist: bionic
        apt_upgrade: false
        apt_update: true
        proxy_protocol: "{{ proxy__protocol }}"
        proxy_host: "{{ proxy__host }}"
        proxy_port: "{{ proxy__port }}"
        no_proxy: "{{ proxy__pass }}"
        set_apt_proxy: true
        set_proxy: true


- name: mysql
  hosts: mysql
  remote_user: root
  roles:
    - role: mysql 
      become: yes
      vars:
        mysql_databases:
          - {name: "{{ mysql_name }}", collation: utf8mb4_unicode_ci, encoding: utf8mb4}
        mysql_users:
          - {name: "{{ mysql_user }}", host: '%', password: "{{ mysql_password }}", priv: "{{ mysql_name }}.*:ALL" }

- name: apply solr configuration
  hosts: solr
  remote_user: root
  roles:
    - role: java
      vars:
        java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
    - role: solr
      vars:
        solr_dist_source_path: https://downloads.apache.org/lucene/solr/8.5.2
        solr_version: 8.5.2

    - role: git
      vars: 
        git_repo: "http://gitlab.upr.edu.cu/vivo/vivo-solr.git"
        git_app_name: vivo-solr


  tasks:
  - name: restart solr
    service:
      name: "solr"
      state: stopped
      enabled: true
  - name: copy to /var/solr/data/
    synchronize:
      src: /opt/vivo-solr/vivocore/
      dest: /var/solr/data/vivocore/
    delegate_to: "{{ inventory_hostname }}"
  - name: permisions
    file: 
      dest: /var/solr/data/vivocore 
      owner: solr 
      group: solr 
      mode: u=rwX,g=rX,o=rX 
      recurse: yes

  - name: restart solr
    service:
      name: "solr"
      state: started
      enabled: true
  environment:
    http_proxy: "{{ proxy__protocol }}://{{ proxy__host }}:{{ proxy__port }}"
    https_proxy: "{{ proxy__protocol }}://{{ proxy__host }}:{{ proxy__port }}"


- name: apply vivo configuration
  hosts: vivo
  remote_user: root
  roles:
    - role: java
      vars:
        java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
    
    - role: maven
      vars:
        maven_proxy_host: "{{ proxy__host }}"
        maven_proxy_port: "{{ proxy__port }}"
        maven_proxy_active: true

    - role: tomcat
      vars:
        tomcat_instances:
          - name: "tomcat-9"
            version: 9
            user: tomcat
            group: tomcat
            shutdown_port: 8019
            non_ssl_connector_port: 8080
            ssl_connector_port: 8443
            ajp_port: 8013
            xms: 512M
            xmx: 1024M
            catalina_max_perm_size: 128m
    - role: apache
      vars:
        apache_mods_enabled:
          - rewrite.load
          - ssl.load
          # - remoteip.load
          - proxy.load
          - proxy_ajp.load
        # apache_haproxy_ip: "200.14.49.24"
        apache_remove_default_vhost: true
        apache_create_vhosts: true
        apache_vhosts:
            - servername: "vivo.upr.edu.cu"
              serveralias: "www.vivo.upr.edu.cu"

    - role: vivo
      vars:
        tomcat_dir: /opt/tomcat-9
        vivo_dir: /opt/vivo
        alias: "vivo.upr.edu.cu"
        vitro_defaultNamespace: "{{ vitro__defaultNamespace }}"
        vitro_database_url : "{{ vitro__database_url }}"
        vitro_solr_url : "{{ vitro__solr_url }}"
        selfEditing_idMatchingProperty : "{{ selfEditing__idMatchingProperty }}"
        tomcat_group: tomcat
        tomcat_user: tomcat
        rootUser_emailAddress: "{{ admin__email }}"
        email_smtpHost : "{{ email__smtpHost }}"
        email_replyTo : "{{ admin__email }}"
  environment:
    http_proxy: "{{ proxy__protocol }}://{{ proxy__host }}:{{ proxy__port }}"
    https_proxy: "{{ proxy__protocol }}://{{ proxy__host }}:{{ proxy__port }}"